config/routes.rb
Rails.application.routes.draw do
  root "task_lists#index"

  devise_for :users

  resources :task_lists, expect: [:destroy] do
    member do
      put  :close
      post :subscribing
      post :unsubscribing
    end
    collection do
      get :favorites
    end
  end

  put "tasks/:id/close", to: "tasks#close", as: 'close_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list, inverse_of: :tasks, required: false
  belongs_to :task_parent, foreign_key: :parent_id, class_name: "Task", required: false, inverse_of: :task_children
  has_many   :task_children, foreign_key: :parent_id, class_name: "Task",
                              dependent: :destroy, inverse_of: :task_parent

  accepts_nested_attributes_for :task_children, reject_if: :all_blank, allow_destroy: true

  validates :description, presence: true

  def check_and_close_tasks!
    close!
    task_children.update_all(done: true)

    if task_parent.present?
      if task_parent.task_children.where(done: false).empty?
        task_parent.close!
      end
    else
      if task_list.tasks.where(done: false, parent_id: nil).empty?
        task_list.close!
      end
    end
  end

  def close!
    update_attribute(:done, true) if open?
  end

  def open?
   !done
  end

  def owner
    task_list.user
  end

end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :user
  has_many   :tasks, dependent: :destroy, inverse_of: :task_list
  has_and_belongs_to_many :favorites_users, class_name: "User"

  validates :name, :user, presence: true

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  scope :public_lists, -> {where(is_public: true)}

  def check_and_close_tasks!
    close!
    tasks.update_all(done: true)
  end

  def close!
    update_attribute(:done, true) if open?
  end

  def open?
    !done
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :task_lists, dependent: :destroy
  has_many :tasks, through: :task_lists
  has_and_belongs_to_many :favorites_task_lists, class_name: "TaskList"

  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  def add_favorite! task_list_id
    task_list = TaskList.find(task_list_id)
    if self.favorites_task_lists.exclude?(task_list)
      self.favorites_task_lists << task_list
    end
  end

  def remove_favorite! task_list_id
    task_list = TaskList.find(task_list_id)
    self.favorites_task_lists.delete(task_list)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @task_lists = current_user.task_lists
  end

  def new
    @task_list = TaskList.new
  end

  def create
    @task_list = current_user.task_lists.new(task_list_params)
    if @task_list.save
      @task_list.tasks.map{|task| task.task_children.update_all(task_list_id: @task_list.id)}
      redirect_to task_lists_path, notice: 'Lista de Tarefas criado com sucesso!'
    else
      render :new
    end
  end

  def edit
    @task_list = current_user.task_lists.find(params[:id])
  end

  def update
    @task_list = current_user.task_lists.find(params[:id])
    if @task_list.update(task_list_params)
      redirect_to task_lists_path, notice: 'Lista de Tarefas atualizada com sucesso!'
    else
      render :edit
    end
  end

  def close
    @task_list = current_user.task_lists.find(params[:id])
    @task_list.check_and_close_tasks!
    redirect_to task_lists_path
  end

  def show
    @task_list = TaskList.find(params[:id])
  end

  def favorites
    @favorites_task_lists = current_user.favorites_task_lists
    @public_task_lists = TaskList.public_lists - @favorites_task_lists
  end

  def subscribing
    current_user.add_favorite! params[:id]
    redirect_to favorites_task_lists_path
  end

  def unsubscribing
    current_user.remove_favorite! params[:id]
    redirect_to favorites_task_lists_path
  end

  private

  def task_list_params
    params.require(:task_list).permit(:name, :is_public, tasks_attributes: [:id, :description,:_destroy, task_children_attributes: [:id, :description, :task_list_id, :_destroy]])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def close
    @task = current_user.tasks.find(params[:id])
    @task.check_and_close_tasks!
    redirect_to task_list_path(@task.task_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
  def finish_task_list_link(task_list)
    link_to fa_icon("times"), close_task_list_path(task_list), method: :put, class: :red if task_list.open? && task_list.user == current_user
  end

  def finish_task_link(task)
    owner = task.task_parent.present? ? task.task_parent.owner : task.owner
    link_to fa_icon("times"), close_task_path(task), method: :put, class: :red if task.open? && owner == current_user
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= name == 'alert' ? "background_yellow" : "background_green" %>">
      <a class="close" onclick="$('.alert').hide()">x</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="sidebar-nav">
  <li class="sidebar-brand">
    <%= link_to "TasksManager", task_lists_path %>
  </li>
  <% if user_signed_in? %>
    <li>
      <%= link_to('Sair', destroy_user_session_path, :method=>'delete') %>
    </li>
    <li>
      <%= link_to('Editar', edit_user_registration_path) %>
    </li>
    <li>
      <%= link_to('Minhas Listas', task_lists_path)%>
    </li>
    <li>
      <%= link_to('Listas Favoritas', favorites_task_lists_path)%>
    </li>
  <% else %>
    <li>
      <%= link_to('Entrar', new_user_session_path)  %>
    </li>
    <li>
      <%= link_to('Cadastrar', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrapper">
      <div id="sidebar-wrapper">
        <%= render 'layouts/navigation' %>
      </div>
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/task_lists/_favorites.html.erb
<div class="well col-md-12">
  <h3>Listas de Tarefas Favoritas</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th width="40%">Nome</th>
        <th width="10%">Fechada?</th>
        <th width="30%">Usuário</th>
        <th width="10%"></th>
      </tr>
    </thead>
    <tbody>
      <% @favorites_task_lists.each do |task_list| %>
        <tr>
          <td><%= link_to task_list.name, task_list_path(task_list) %></td>
          <td><%= t("boolean_#{task_list.done?}") %></td>
          <td><%= task_list.user.email %></td>
          <td>
            <%= link_to unsubscribing_task_list_path(task_list.id), method: :post do%>
              <i class="yellow fa fa-star" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/task_lists/_form.html.erb
<%= form_for @task_list do |f| %>
  <% if @task_list.errors.any? %>
    <ul class="well background_red">
      <% @task_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="checkbox">
    <label><%= f.check_box :is_public %> Público?</label>
  </div>
  <div class="well form-group">
    <%= f.fields_for :tasks do |task| %>
      <%= render 'task_fields', f: task %>
    <% end %>
    <%= link_to_add_association "Adicionar Tarefa", f, :tasks, class: "btn btn-primary" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Salvar', class: "btn btn-primary"%>
    <%= link_to 'Minhas Listas', task_lists_path, class: "btn btn-default"%>
  </div>
<% end %>

app/views/task_lists/_publics.html.erb
<div class="well col-md-12">
  <h3>Listas de Tarefas Públicas</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th width="40%">Nome</th>
        <th width="10%">Fechada?</th>
        <th width="30%">Usuário</th>
        <th width="10%"></th>
      </tr>
    </thead>
    <tbody>
      <% @public_task_lists.each do |task_list| %>
        <tr>
          <td><%= link_to task_list.name, task_list_path(task_list) %></td>
          <td><%= t("boolean_#{task_list.done?}") %></td>
          <td><%= task_list.user.email %></td>
          <td>
            <%= link_to subscribing_task_list_path(task_list.id), method: :post do %>
              <i class="yellow fa fa-star-o" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/task_lists/_task_child_fields.html.erb
<div class="well nested-fields">
  <div class="form-group">
    <%= f.label :description, "Nome" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= link_to_remove_association "Remover SubTarefa", f, class: "btn btn-default" %>
  </div>
  <hr />
</div>

app/views/task_lists/_task_children.html.erb
<div class="well-dark row">
  <table class="table">
    <thead>
      <tr>
        <th width="34%">SubTarefas</th>
        <th width="33%"></th>
        <th width="33%"></th>
      </tr>
    </thead>
    <tbody>
      <% task.task_children.each do |task_child| %>
        <tr>
          <td><%= task_child.description %></td>
          <td><%= t("boolean_#{task_child.done?}") %></td>
          <td><%= finish_task_link(task_child) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/task_lists/_task_fields.html.erb
<div class="well nested-fields">
  <div class="form-group">
    <%= f.label :description, "Nome" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="well form-group">
    <%= f.fields_for :task_children do |task_child| %>
      <%= render 'task_child_fields', f: task_child %>
    <% end %>
    <%= link_to_add_association "Adicionar SubTarefa", f, :task_children, class: "btn btn-primary" %>
  </div>
  <div class="form-group">
    <%= link_to_remove_association "Remover Tarefa", f, class: "btn btn-default" %>
  </div>
  <hr />
</div>

app/views/task_lists/edit.html.erb
<h1>Editar Lista de Tarefas</h1>

<%= render 'form' %>

app/views/task_lists/favorites.html.erb
<div class="row">
  <%= render 'publics' %>
</div>
<div class="row">
  <%= render 'favorites' %>
</div>

app/views/task_lists/index.html.erb
<div class="row">
  <div class="well col-md-12">
    <h3>Minhas Listas de Tarefas</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th width="40%">Nome</th>
          <th width="10%">Publica?</th>
          <th width="10%">Fechada?</th>
          <th width="10%"></th>
        </tr>
      </thead>
      <tbody>
        <% @task_lists.each do |task_list| %>
          <tr>
            <td><%= link_to task_list.name, task_list_path(task_list) %></td>
            <td><%= t("boolean_#{task_list.is_public?}") %></td>
            <td><%= t("boolean_#{task_list.done?}") %></td>
            <td><%= finish_task_list_link(task_list)%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'Nova Lista', new_task_list_path, class: "btn btn-primary" %>
</div>

app/views/task_lists/new.html.erb
<h1>Nova Lista de Tarefas</h1>

<%= render 'form' %>

app/views/task_lists/show.html.erb
<div id="main" class="container-fluid">
 <h3 class="page-header">Lista de Tarefas - <%= @task_list.name %></h3>
  <div id="notice"></div>
  <div class="row">
    <div class="col-md-4">
      <p><strong>Pública?</strong></p>
      <p><%= t("boolean_#{@task_list.is_public?}")%></p>
    </div>
    <div class="col-md-4">
      <p><strong>Fechada?</strong></p>
      <p><%= t("boolean_#{@task_list.done?}") %></p>
    </div>
    <div class="col-md-4">
      <p><strong>Usuário</strong></p>
      <p><%= @task_list.user.email %></p>
    </div>
  </div>
  <hr />
  <div class="row">
    <% @task_list.tasks.where(parent_id: nil).order(:created_at).each do |task| %>
      <div class="well row">
        <div class="col-md-4">
          <h4>Tarefa - <%= task.description %></h4>
        </div>
        <div class="col-md-4">
          <p><b>Fechado?</b> - <%= t("boolean_#{task.done?}") %></p>
        </div>
        <div class="col-md-4">
          <p><%= finish_task_link(task) %></p>
        </div>
        <%= render partial: 'task_children', locals: {task: task}%>
      </div>
    <% end %>
  </div>
</div>
<div id="actions" class="row">
  <div class="col-md-12">
    <%= link_to("Editar", edit_task_list_path(@task_list), class: "btn btn-primary") if( @task_list.user == current_user) %>
    <% if @task_list.user == current_user %>
      <%= link_to "Voltar", task_lists_path, class: "btn btn-default" %>
    <% else %>
      <%= link_to "Voltar", favorites_task_lists_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>